// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBni_hAlHMtt8cRKU7KjBVTtOsEcAvwRF4',
    appId: '1:11199189138:web:a83d29e12b6295308e564b',
    messagingSenderId: '11199189138',
    projectId: 'sakura-petty-money-tracker',
    authDomain: 'sakura-petty-money-tracker.firebaseapp.com',
    storageBucket: 'sakura-petty-money-tracker.firebasestorage.app',
    measurementId: 'G-BT6MNETGF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTfCLbTkvUW8yGyI0tTDG-1fobfXUT8lY',
    appId: '1:11199189138:android:9a5b2c861b1ed2a78e564b',
    messagingSenderId: '11199189138',
    projectId: 'sakura-petty-money-tracker',
    storageBucket: 'sakura-petty-money-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASds-lC2rrG1MtRMyyZaFdW7njdcYK25E',
    appId: '1:11199189138:ios:88b882d05e8245b48e564b',
    messagingSenderId: '11199189138',
    projectId: 'sakura-petty-money-tracker',
    storageBucket: 'sakura-petty-money-tracker.firebasestorage.app',
    iosBundleId: 'com.example.selabProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASds-lC2rrG1MtRMyyZaFdW7njdcYK25E',
    appId: '1:11199189138:ios:88b882d05e8245b48e564b',
    messagingSenderId: '11199189138',
    projectId: 'sakura-petty-money-tracker',
    storageBucket: 'sakura-petty-money-tracker.firebasestorage.app',
    iosBundleId: 'com.example.selabProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBni_hAlHMtt8cRKU7KjBVTtOsEcAvwRF4',
    appId: '1:11199189138:web:402a188968b831b28e564b',
    messagingSenderId: '11199189138',
    projectId: 'sakura-petty-money-tracker',
    authDomain: 'sakura-petty-money-tracker.firebaseapp.com',
    storageBucket: 'sakura-petty-money-tracker.firebasestorage.app',
    measurementId: 'G-3HKWTG1HWD',
  );

}